# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "perk/ubuntu-2204-arm64"

  vms = [
    { name: "web1", ssh_port: 50022 },
    { name: "web2", ssh_port: 50023 },
  ]

  vms.each do |vm|
    config.vm.define vm[:name] do |node|
      node.vm.hostname = vm[:name]

      node.vm.provider "qemu" do |qe|
        qe.arch = "aarch64"
        qe.machine = "virt,accel=hvf,highmem=on"
        qe.cpu = "host"
        qe.smp = "cpus=1,sockets=1,cores=1,threads=1"
        qe.memory = "1024"
        qe.net_device = "virtio-net-pci"
        qe.ssh_port = vm[:ssh_port]
      end
    end
  end
end